name: Deploy scripts

on:
  workflow_run:
    workflows: [ "Run all tests" ]
    branches: [ main ]
    types:
      - completed

env:
  STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
  STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
  STEAM_SHARED_SECRET: ${{ secrets.STEAM_SHARED_SECRET }}
  MOD_IO_ACCESS_TOKEN: ${{ secrets.MOD_IO_ACCESS_TOKEN }}

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Download packages required for generating Steam auth code
        run: cd "${GITHUB_WORKSPACE}/.github/scripts" && npm install
      - name: Setup SteamCMD
        id: setup-steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      - name: Download scripts from Steam Workshop
        run: ${GITHUB_WORKSPACE}/.github/scripts/download-workshop-items.bash
      - name: Deploy scripts
        run: ${GITHUB_WORKSPACE}/.github/scripts/deploy.bash