name: dotnet package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Decrypt shared libraries
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SHARED_LIBRARIES_PASSWORD }}" --output shared-libraries.tar.gz shared-libraries.tar.gz.gpg
      - name: Extract shared libraries
        uses: a7ul/tar-action@v1.1.0
        id: extract
        with:
          command: x
          files: shared-libraries.tar.gz
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal